"""
Django settings for eventapis project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# MEDIA_ROOT sẽ xác định nơi upload ảnh
MEDIA_ROOT = '%s/events/static/' % BASE_DIR
STATICFILES_DIRS = [BASE_DIR / 'static']

TIME_ZONE = 'Asia/Saigon'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9!hvs50q!$cwbo!7gqo57-a-dmo-v)lk)ubh))2!j*mcyvg(@b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '346d-171-250-11-112.ngrok-free.app',  # thêm ngrok domain vào đây
]

SITE_ID = 3

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'events.apps.EventsConfig',  # Ta cần cho django biết về sự tồn tại của module event thông qua biến INSTALLED_APPS
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'rest_framework.authtoken',
    'oauth2_provider',

    # Google
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'allauth.account.middleware.AccountMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {"access_type": "online"}
    }
}

ROOT_URLCONF = 'eventapis.urls'

CKEDITOR_UPLOAD_PATH = "ckeditors/events"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eventapis.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Cấu hình cho kết nối đến CSDL MySQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'eventdb',
        'USER': 'root',
        'PASSWORD': 'admin123',
        'HOST': ''  # mặc định localhost
    }
}
import pymysql

pymysql.install_as_MySQLdb()

# Chỉ định lớp model đại diện cho một User, mặc định là “auth.User”.
AUTH_USER_MODEL = 'events.User'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import cloudinary
import cloudinary.uploader
from cloudinary.utils import cloudinary_url

# Configuration
cloudinary.config(
    cloud_name="doi6ayqri",
    api_key="658164331927654",
    api_secret="506_HMPvosnq-znGAu0Q-t12EVo",  # Click 'View API Keys' above to copy your API secret
    secure=True
)

# Cấu hình cho REST framework để sử dụng OAuth2 cho xác thực
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Cấu hình cho OAuth2 provider, sử dụng JSONAuthLibCore để xử lý xác thực
OAUTH2_PROVIDER = {
    # parses OAuth2 data from application/json requests
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',

    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,  # 1 hour
    'REFRESH_TOKEN_EXPIRE_SECONDS': 2592000,  # 30 days
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope'},
}

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend"
)

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

AUTH_USER_MODEL = 'events.User'

# Hoàng
# Client_id : MBK54ICEHKmaUKKGwkhxUH0ZYYJpgvGqNelJIuSi
# Client_secret: RxpHCMTeO0Ixf2V5sC3KXcKUhNTya5kwNjynP3O5mCsQaUPjordWQvwsAle1aDxAhH9x0uaQ0dunwp9B9xNrxN4NPmejBXi1YDMLHJuqjAKxENvds93HPBM6K7qiq3sF

# Quân
# DEFAULT_OAUTH2_CLIENT_ID = 'LUQb13fIsa3mF5nnBakoDDTorY4Hhm88LUw429uz'
# Client_secret = 'SzdKbmdauALjzHrr6GYZcJ5II4PGc6QcVxyM0Z7NxyelDZp3ZSnORXgNemSekVY2yABSAlrPlsQBlcEqbSOFIxaDsHk1kqPVdJgANvjD8RbvyCRf0OTP42bYdIVD47We'

# GOOGLE_CLIENT_ID = '803363646882-969u7bsui6ujmr0g9tumrenlqsgjb2o9.apps.googleusercontent.com'
# GOOGLE_OAUTH2_SECRET = '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'


# VNPAY CONFIG
VNPAY_TMN_CODE = 'LPXTIU1F'
VNPAY_HASH_SECRET_KEY = '71GVT9UD1D6SUY4CVI81MCUUYF6SQT48'
VNPAY_PAYMENT_URL = 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html'
VNPAY_API_URL = 'https://sandbox.vnpayment.vn/merchant_webapi/api/transaction'
VNPAY_RETURN_URL = 'http://127.0.0.1:8000/payments/return/'

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '2251050031hoang@gmail.com'
EMAIL_HOST_PASSWORD = 'yvcx rxva vwdg amba'
DEFAULT_FROM_EMAIL = '2251050031hoang@gmail.com'


