# Generated by Django 5.2 on 2025-04-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_payment_payment_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('ticket',)},
        ),
    ]
