# Generated by Django 5.2 on 2025-04-24 16:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_at_event_updated_at_user_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ticket_price',
            new_name='ticket_price_regular',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='video_url',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price_vip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
