# Generated by Django 5.2 on 2025-04-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_end_time_event_start_time_and_more'),
        ('events', '0004_alter_event_image_alter_event_video'),
    ]

    operations = [
    ]
